# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b7b6d7b7289a745b83310fda309410eb9c6809ecfd846e4d178e2814744ce23d08e696a82d32861f40a5ff5834dad05bc79b988faa7725f214469925046c105

test:
  secret_key_base: 6c648a1a0cf21d3a8b9a1622e78477bd73ef7223d6141fe41da619fbc7ab952cf00fddcdc50d733e1da40a0df431182c9b34bdb59c44f8341ad5e93b1518abed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
